namespace Arrowgene.ENet.Protocol
{
    public enum ENetProtocolCommand : byte
    {
        ENET_PROTOCOL_COMMAND_NONE               = 0,
        ENET_PROTOCOL_COMMAND_ACKNOWLEDGE        = 1,
        ENET_PROTOCOL_COMMAND_CONNECT            = 2,
        ENET_PROTOCOL_COMMAND_VERIFY_CONNECT     = 3,
        ENET_PROTOCOL_COMMAND_DISCONNECT         = 4,
        ENET_PROTOCOL_COMMAND_PING               = 5,
        ENET_PROTOCOL_COMMAND_SEND_RELIABLE      = 6,
        ENET_PROTOCOL_COMMAND_SEND_UNRELIABLE    = 7,
        ENET_PROTOCOL_COMMAND_SEND_FRAGMENT      = 8,
        ENET_PROTOCOL_COMMAND_SEND_UNSEQUENCED   = 9,
        ENET_PROTOCOL_COMMAND_BANDWIDTH_LIMIT    = 10,
        ENET_PROTOCOL_COMMAND_THROTTLE_CONFIGURE = 11,
        ENET_PROTOCOL_COMMAND_SEND_UNRELIABLE_FRAGMENT = 12,
        ENET_PROTOCOL_COMMAND_COUNT              = 13,

        ENET_PROTOCOL_COMMAND_MASK               = 0x0F
    }
}
